apiVersion: monitoring.coreos.com/v1                                                                                                                                                                        
kind: ServiceMonitor
metadata:
  name: cloudbees-masters
  namespace: prometheus-operator
  labels:
    release: prometheus-operator
spec:
  endpoints:
  - interval: 10s 
    port: http
    path: "this will be relabeled"
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_label_com_cloudbees_cje_tenant]
      regex: (.*)
      replacement: /${1}/prometheus
      targetLabel: __metrics_path__
  selector:
    matchLabels:
      com.cloudbees.cje.type: master
  namespaceSelector:
    matchNames:
    - cloudbees
